apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-pub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-pub
  template:
    metadata:
      labels:
        app: voting-pub
    spec:
      containers:
      - name: pub
        image: gcr.io/tensile-imprint-439410-s4/voting-pub
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"