apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "votes"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DJANGO_DB_HOST: "postgres"
  DJANGO_DB_PORT: "5432"