apiVersion: v1
kind: Service
metadata:
  name: postgres  # This name must match the DB_HOST env variable
spec:
  selector:
    app: postgres  # Must match the label in postgres deployment
  ports:
  - port: 5432
    targetPort: 5432