version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres-test
    environment:
      - POSTGRES_DB=votes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=votes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
    depends_on:
      - postgres

volumes:
  postgres_data: