# Generated by Django 5.1.4 on 2024-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('partyname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_number', models.IntegerField()),
                ('ballotbox_no', models.IntegerField()),
                ('partyname', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
            options={
                'unique_together': {('city_number', 'ballotbox_no', 'partyname')},
            },
        ),
    ]
